#!/bin/bash

## VARIABLES
sshPort="2223"
networkCIDR="10.10.200.0/24"
localhostIP="10.10.200.219"
## - VARIABLES

rm /etc/apt/sources.list.d/pve-enterprise.list

echo '# Proxmox community package repository' >> /etc/apt/sources.list
echo 'deb http://download.proxmox.com/debian/pve bullseye pve-no-subscription' >> /etc/apt/sources.list

apt update
apt upgrade
apt dist-upgrade

apt install htop gzip

adduser alex
# usermod -aG adm alex
usermod -aG sudo alex

## ssh config


## start scripts
bash iptables-for-proxmox $sshPort $networkCIDR $localhostIP