#!/bin/bash

## ARGUMENTS
# $1 : IP address
# $2 : Port
ssh_port=$1
network_host=$2
bastion=$3

# Check if sshPort not empty
if [ -z "$ssh_port" ]; then
	printf "ERROR: ssh_port is empty\n";
	exit 1;
fi

if [ -z "$network_host" ]; then
	printf "ERROR: network host is empty\n";
	exit 1;
fi

# Check if localhostIP not empty
if [ -z "$bastion" ]; then
	printf "ERROR: bastion is empty\n";
	exit 1;
fi

# rules for ping
iptables -t filter -A INPUT -p icmp -j ACCEPT
iptables -t filter -A OUTPUT -p icmp -j ACCEPT

# SSH entries (bastion)
iptables -I INPUT -p tcp --dport $ssh_port -j DROP
iptables -I INPUT -s $bastion -p tcp --dport $ssh_port -j ACCEPT
# VM entries
iptables -I INPUT -s $network_host -p tcp --dport $ssh_port -j ACCEPT

# List all rules
iptables -L --line-numbers
# iptables -D INPUT 1