#!/bin/bash

############
## COLORS ##
############
nocolor='\033[0m'
whiite='\033[0;97m'
whiitebold='\033[0;1;97m'
purple='\033[0;38;5;201m'
blue='\033[0;38;5;45m'
blueblink='\033[0;5;38;5;45m'
darkblue='\033[0;38;5;27m'
green='\033[0;32m'
greendim='\033[0;3;32m'
yellow='\033[0;38;5;178m'
orange='\e[38;5;166;3m'
orangeital='\e[0;3;38;5;166m'
gray='\033[0;38;5;249m'
graybold='\033[0;1;38;5;249m'
graydim='\033[0;2;38;5;250m'
red='\033[0;91m'
## CUSTOM
# c__fctName='\033[0;38;5;45m'
c__fctName=$whiitebold
c__fctAction=$graydim
c__fct2=$gray
c__msgVar=$graybold
c__value=$blue
c__error=$red
c__success=$green

. ./prox.conf

printf "${c__fctName}GLOBAL${nocolor}\n"
printf "${c__fctAction}proxmox${nocolor}: ${c__value}$proxmox${nocolor}\n"

printf "${c__fctAction}init iptables${nocolor}: ${c__value}$init_iptables${nocolor}\n"
printf "${c__fctAction}init ssh${nocolor}: ${c__value}$init_ssh${nocolor}\n"
printf "\n"

printf "${c__fctName}USERS${nocolor}\n"
printf "${c__fctAction}init users${nocolor}: ${c__value}$init_users${nocolor}\n"
printf "${c__fctAction}groups string${nocolor}: ${c__value}$groups_str${nocolor}\n"
printf "\n"

printf "${c__fctName}NETWORK${nocolor}\n"
printf "${c__fctAction}init iptables${nocolor}: ${c__value}$init_iptables${nocolor}\n"
printf "${c__fctAction}Network host${nocolor}: ${c__value}$network_host${nocolor}\n"
printf "${c__fctAction}Bastion IP${nocolor}: ${c__value}$bastion_ip${nocolor}\n"
printf "\n"

printf "${c__fctName}SSH${nocolor}\n"
printf "${c__fctAction}init SSH${nocolor}: ${c__value}$init_ssh${nocolor}\n"
printf "${c__fctAction}SSH Port${nocolor}: ${c__value}$ssh_port${nocolor}\n"
printf "${c__fctAction}Allow users${nocolor}: ${c__value}$ssh_allowed_users${nocolor}\n"
printf "${c__fctAction}Allow groups${nocolor}: ${c__value}$ssh_allowed_groups${nocolor}\n"
printf "${c__fctAction}Denied users${nocolor}: ${c__value}$ssh_denied_users${nocolor}\n"
printf "${c__fctAction}Denied groups${nocolor}: ${c__value}$ssh_denied_groups${nocolor}\n"
printf "\n"