#!/bin/bash

## VARIABLES
sshd_config="files/etc/ssh/sshd_config"
PWD=$(pwd)


# Check if the script is being run with root privileges
# if [ "$EUID" -ne 0 ]; then
#     echo "Please run this script as root."
#     exit 1
# fi

# Récupération des paramètres en utilisant getopts
while [[ $# -gt 0 ]]; do
  case $1 in
    --allowedusers)
      shift
      allowed_users=($(echo "$1" | tr ',' ' '))
      ;;
    --allowedgroups)
      shift
      allowed_groups=($(echo "$1" | tr ',' ' '))
      ;;
    --deniedusers)
      shift
      denied_users=($(echo "$1" | tr ',' ' '))
      ;;
    --deniedgroups)
      shift
      denied_groups=($(echo "$1" | tr ',' ' '))
      ;;
    --sshport)
      shift
      ssh_port=$1
      ;;
    --networkcidr)
      shift
      network_cidr=$1
      ;;
    *)
      echo "Option invalide: $1"
      exit 1
      ;;
  esac
  shift
done

CheckMandatoryParams() {
	# Vérification des paramètres obligatoires
	if [[ -z $ssh_port ]]; then
		echo "Le paramètre --sshport est obligatoire."
		exit 1
	fi

	if [[ -z $network_cidr ]]; then
		echo "Le paramètre --networkcidr est obligatoire."
		exit 1
	fi
}


DisplayValues() {
	## Affichage values
	# Configuration des utilisateurs autorisés
	if [[ ${#allowed_users[@]} -gt 0 ]]; then
		echo "AllowUsers ${allowed_users[*]}"
	fi

	# Configuration des groupes autorisés
	if [[ ${#allowed_groups[@]} -gt 0 ]]; then
		echo "AllowGroups ${allowed_groups[*]}"
	fi

	# Configuration des utilisateurs non-autorisés
	if [[ ${#denied_users[@]} -gt 0 ]]; then
		echo "DenyUsers ${denied_users[*]}"
	fi

	# Configuration des groupes non-autorisés
	if [[ ${#denied_groups[@]} -gt 0 ]]; then
		echo "DenyGroups ${denied_groups[*]}"
	fi

	# Configuration du port SSH
	echo "Port $ssh_port"

	# Configuration du CIDR réseau
	echo "ListenAddress $network_cidr"
}


SavePreviousFile() {
	# Sauvegarde du fichier de configuration original
	cp $sshd_config $sshd_config.backup
}

UpdateConfig() {
	printf "${gray}Start reconfiguring ...${nocolor}\n"
	# lancement de la re-config
	# sudo ./scripts/update-ssh-config -k Port -v $ssh_port
	# sudo ./scripts/update-ssh-config -k ListenAddress -v $network_cidr
	# sudo ./scripts/update-ssh-config -k AllowUsers -v $allowed_users
	# sudo ./scripts/update-ssh-config -k AllowGroups -v $allowed_groups
	# sudo ./scripts/update-ssh-config -k DenyUsers -v $denied_users
	# sudo ./scripts/update-ssh-config -k DenyGroups -v $denied_groups
}

DisplayConfig() {
	cat "$sshd_config"
}